### ISSUE TITLE
Add nodename to API output

### ISSUE THREAD

**Issue by wvengen** [q-m/scrapyd-k8s#13]
Scrapyd returns a `node_name` in API responses. Implement that here too.
This can be used by scrapyd clients when working with multiple scrapyd servers.

https://scrapyd.readthedocs.io/en/latest/api.html
https://github.com/scrapy/scrapyd/blob/master/scrapyd/webservice.py

**Comment by wvengen** [comment]
Not sure yet what the node_name would point to. Ideas?

- hostname of the machine running Docker (Docker), or the name+namespace of the scrapyd-k8s deployment (Kubernetes)
- hostname of the machine running Docker (Docker), or the node name (Kubernetes)
- container ID (docker), or the job name (Kubernetes).
- ...

**Comment by wvengen** [comment]
Let's start with:
* hostname of the machine running Docker (Docker) - if we can get it from the Docker daemon
* node name (Kubernetes)

If you have a better idea, please discuss it here, but when starting to develop this, stick to the above (until we have something better).

**Comment by RoelAdriaans** [comment]
Worked on by Marielle and Cas

**Comment by vlerkin** [comment]
I added the changes you asked for, now we have MY_DEPLOYMENT_NAME as an env var in Kubernetes and node name for k8s is represented like this ```<deployment_name>.<namespace>```

When I use Docker container and access API via browser, the result is:
```{"node_name":"fe64beb15b9d","projects":["example"],"status":"ok"}```

When I run k8s and access API via curl, I get the result:
```
valeriiaklestova@BA92-HC7TN99KW6 scrapyd-k8s % curl http://localhost:6800/listprojects.json      
{"node_name":"scrapyd-k8s.default","projects":["example"],"status":"ok"}
```

Going to make a PR with both issues: #13 and #22.

**Comment by vlerkin** [comment]
However I do have some problems (500 error) for two endpoints:
```curl -F project=example -F _version=latest -F spider=quotes http://localhost:6800/schedule.json```
```curl http://localhost:6800/listjobs.json```

Looking into it to understand why it causes a problem.

**Comment by vlerkin** [comment]
If I look into logs, it seems that the error is due to Kubernetes misconfiguration and is not connected to the changes I made in the code:

```
>   File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'ad1e5bc3-a98d-4d24-92e5-e1d2371f03b7', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '60d78d2f-a4fb-4502-99a6-b748874bf59e', 'X-Kubernetes-Pf-Prioritylevel-Uid': '173f6657-26e1-4d0c-8cd0-1bdfea5ce35d', 'Date': 'Wed, 06 Mar 2024 18:11:13 GMT', 'Content-Length': '313'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"jobs.batch is forbidden: User \"system:serviceaccount:default:scrapyd-k8s\" cannot list resource \"jobs\" in API group \"batch\" in the namespace \"scrapyd\"","reason":"Forbidden","details":{"group":"batch","kind":"jobs"},"code":403}
```
