### ISSUE TITLE
Finish daemonstatus endpoint

### ISSUE THREAD

**Issue by wvengen** [q-m/scrapyd-k8s#23]
The endpoint `GET /daemonstatus.json` does not return what is expected from scrapyd. Make it so.
https://scrapyd.readthedocs.io/en/latest/api.html#daemonstatus-json

**Comment by wvengen** [comment]
@vlerkin if you could pick this up before looking at scheduling, that would be great - it is a simple issue that would be good to have fixed.

**Comment by vlerkin** [comment]
Ok, I will take this one next, no problem

**Comment by vlerkin** [comment]
Submitted a PR
