### ISSUE TITLE
Add basic auth

### ISSUE THREAD

**Issue by wvengen** [q-m/scrapyd-k8s#3]
As a small security measure, optional basic auth could be added (so that cluster access does not mean scrapyd access).
Try to keep the configuration for this the same as scrapyd: https://scrapyd.readthedocs.io/en/latest/config.html#username

**Comment by RoelAdriaans** [comment]
Worked on by Jeremy and Boudewijn

**Comment by wvengen** [comment]
Thanks for working on this?
Just to check if it makes sense to use https://flask-basicauth.readthedocs.io/ did you check that as well?

**Comment by BoudewijnZwart** [comment]
Yes we looked at it and it is definitely a good option. Implementing it yourself gives you more flexibility but using flask-basicauth might be easier/ more proven. I can change the code to use flask-basicauth pretty easily if you want to go that way.

Shall I look into it?

**Comment by wvengen** [comment]
I think that would be helpful, yes :+1:
I expect something like this uses very little code in the project, keep it simpler.

**Comment by BoudewijnZwart** [comment]
I changed the code to use the flask-basicauth package with minimal amount of code. You can enable the authorization by uncommenting the username and password in the config file. If you do this all of the endpoints need authorization. Is that the desired behavior or do some endpoints need to always be public?

Maybe it would also be smart to limit or log failed login attempts.
